### PR TITLE
Add Dataset#except_strategy, choosing the EXCEPT emulation strategy

### PR DESCRIPTION
**Pull request by jeremyevans**
This adds the ability to use NOT EXISTS, NOT IN, and LEFT JOIN
EXCEPT emulations instead of the default strategy of using UNION
ALL and GROUP BY. Example:

```ruby
ds1.except_strategy(:group_by, nil).except(ds2)
ds1.except_strategy(:not_exists, :column).except(ds2)
ds1.except_strategy(:not_in, :column).except(ds2)
ds1.except_strategy(:left_join, :column).except(ds2)
```

The UNION ALL/GROUP BY strategy remains the default, as that is
the only emulation that does not require a key column.

The advantage of this approach of choosing a strategy is there
may be certain queries that are more performant using one
strategy, and other queries that are more performant using
a different strategy.

### CODE REVIEW

**Comment by aguynamedryan** [comment]
This looks awesome.  Could you please make it possible to define more than one column to match on?  Thanks!

**Comment by jeremyevans** [comment]
I think that should be possible, except for the NOT IN emulation, as I don't think Impala supports composite values in NOT IN (according to http://www.cloudera.com/documentation/archive/impala/2-x/2-1-x/topics/impala_subqueries.html).

**Comment by jeremyevans** [comment]
OK, I pushed another commit that supports multiple keys for the NOT EXISTS and LEFT JOIN strategies.

**Comment by aguynamedryan** [comment]
Awesome!  Thank you very much!

**Pull request merged**
